### ISSUE TITLE
Suggestions for Wraith

### ISSUE THREAD

**Issue by EchoGravity** [LoneDev6/Issues-Wraith#1]
Implement a enable checks option to wraith.

IE: 

KillAura
Enabled: false

Fly:
Enabled: True

This gives the user the ability to disable certain checks they don't want.

You could also make a checks GUI that has all the checks. Any enabled checks as green wool and any disabled checks as red wool. Clicking on a check toggles whether it's enabled or not.

Also, you could add an option to auto-ban clients.
For example, when a player joins they must click a message (same as the client test feature) and if they fail after 10 seconds they get kicked. After a second time, a custom command can be run such as ban %player% WRAITH CHEAT CLIENT DETECTION

This would remove 95% of cheaters before they even get the chance to cheat.

**Comment by LoneDev6** [comment]
Thanks for the suggestions, each of these suggestions (beside the GUI one) are implemented.
I will see if I can add a GUI but right now the important thing is to get a stable anticheat
