### ISSUE TITLE
[BUG] NoFallSkid - false positive

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#11]
the nofallskid is broken.
when someone is fall or disconnect and connect and fall when he falls from high place the anti-cheat kick him.
when he wants to get back into the server after he got the kick its not let him in its always kick him and say: nofallskid detected

when player fall or use laddres the anti cheat flags it as nofall hack in set them on a kick loop, also, if a player joins the server there is a few seconds untill it loads where it floats, but now it flags it as flight and goes into a kick loop

and the normal nofall is broken. if you fall from high place without die the anti-cheat will kill you.
[fail NoFall field (A)]

**Comment by LoneDev6** [comment]
Interesting, thanks I will fix this false positive

**Comment by LoneDev6** [comment]
Should be fixed in the new update I will publish
