### ISSUE TITLE
the nofallskid still broken

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#12]
The nofallskid kick random players.
I checked the players they are not useing hax and the anti-cheat always kick them.
(failed nofall-skid check)

(sometimes if you fly with elytra and landing the anti-cheat will kill you)

(the anti cheat doesn't stop the cheat: jetpack)

Please fix the plugin
(great plugin)

**Comment by LoneDev6** [comment]
Elytra should be fixed in the new update.

Please give me more details of random kicks as I've never experienced them. Make videos or give me location screenshot of where they landed.

Thanks!
