### ISSUE TITLE
Various cheat modules from free public clients are undetected

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#14]
Many cheat modules were tested using the Anti-cheat and sadly the large sum of them have not been detected, some even not being detected when set to "No anticheat bypass / Vanilla"
Said cheat modules include basic movement cheats such as Speed(does get detected ONLY at high speeds), Midair jumps, Jetpack, Bhop, Jesus hacks and more.
alongside that miscellaneous cheat modules such as Chestaura (steals nearby chest loot in a fraction of a second), Phase, Ghost hand (allows you to hit players / loot chests through walls)
and combat cheats such as Killaura Multiaura and also a cheat called "Infinite Aura" allowing you to hit players up to 120 blocks away (Module exists on the Free version of Sigma5 which is public) 
-Note that infinite aura is not detected allthough it has NO Anti-cheat bypasses, meaning being able to be used while an anticheat is active is concerning.

**Comment by LoneDev6** [comment]
Hello!
Currently this anticheat had not being updated since some months ago, I surely have to rework on it as most cheats got updated.
Thanks for your patience

**Comment by Ofek270704** [comment]
and i have an idea.
I put the test client in my hub, and i think you need to add set position for this client when you joining the server the plugin is teleport you to one position and test your client.

**Comment by Ofek270704** [comment]
btw nice work great anti cheat!

**Comment by LoneDev6** [comment]
> 
> 
> and i have an idea.
> I put the test client in my hub, and i think you need to add set position for this client when you joining the server the plugin is teleport you to one position and test your client.

I think it would be too annoying to legit players



> 
> 
> btw nice work great anti cheat!

thanks mate! I wish I could find time to recode the base of this anticheat in order to cover most recent cheats. I may find it next week

**Comment by Ofek270704** [comment]
> > and i have an idea.
> > I put the test client in my hub, and i think you need to add set position for this client when you joining the server the plugin is teleport you to one position and test your client.
> 
> I think it would be too annoying to legit players


its wouldn't annoying legit players do it an option to turn off.
I have a bungeecord server

**Comment by Ofek270704** [comment]
May you build a permission for admin and moderators, I want they see the plugins but not all the plugins.

**Comment by Ofek270704** [comment]
May you make an option for the test client to be in one position. if it would be too annoying to legit players make an option in the config to disable it. (i am really need it to my server and i think more people need it).

**Comment by LoneDev6** [comment]
So you need an option to teleport the player on a specific test area and test them for killaura and other hacks?
If yes this won't work as hacker will notice and disable cheats, so it will look like they are clean

**Comment by Ofek270704** [comment]
> So you need an option to teleport the player on a specific test area and test them for killaura and other hacks?
> If yes this won't work as hacker will notice and disable cheats, so it will look like they are clean

I want it teleport you and check client in on position.
I need it for my hub.
I have a bungeecord server

**Comment by Ofek270704** [comment]
When player join to the hub its teleport him to the position, I set before and test his client.

**Comment by Ofek270704** [comment]
May you tell me how I whitelist badlion?

**Comment by Ofek270704** [comment]
May you help me with the testclient in the hub?

**Comment by LoneDev6** [comment]
Hello please, this is not a chat, if you need direct help contact me via PM on SpigotMC.org

> 
> 
> May you tell me how I whitelist badlion?

Anyway badlion should already be whitelisted as if I recall I cannot detect it directly.




> 
> 
> May you help me with the testclient in the hub?

I won't add this feature as it's basically useless, why do you want to test a client? As I said the hacker will disable hacks when it gets teleported to the test area
