### ISSUE TITLE
TestClient [BUG] 

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#17]
the test client doesn't stop this hacks: https://inertiaclient.com/

**Comment by Ofek270704** [comment]
all the cheats with via version the test client doesn't stop them.

**Comment by Ofek270704** [comment]
if the via version is off the test client has detected it. if the hacker turns on the via version the test client is not detected it

**Comment by Ofek270704** [comment]
I mean the hacker has inside the cheats the cheat: ''via version''

**Comment by LoneDev6** [comment]
Sadly the testclient can't detect all cheats, it detect some cheats that expose their name during server login process
