### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EchoGravity** [LoneDev6/Issues-Wraith#2]
Message Error/Typo
SpigotMC Page says 99% but ingame it says 90%

![image](https://user-images.githubusercontent.com/55660010/86162805-4aa95d00-bb07-11ea-81af-09364327045d.png)
![image](https://user-images.githubusercontent.com/55660010/86162807-4b41f380-bb07-11ea-8a5b-ce27b9059d9e.png)

**Comment by LoneDev6** [comment]
Done, thanks a lot
