### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BadSuzy** [LoneDev6/Issues-Wraith#20]
**Describe the bug**
Redstone circuitry using an observer, few repeaters with a delay of 4, running to a sticky piston with a block in front of it.  Placing Bamboo, sugar cane, in front of the observer, causes the stickypiston with the block attached to push the bamboo or sugarcane, which causes a 0 tick error even when there are repeaters with a delay of 4 set down

**To Reproduce**
1. Place down your circuitry, Redstone, 3 or more Repeaters with a delay of 4. Set sticky piston in position
2. Run redstone from them to the stickypiston with the block attached. 
3. Place Bamboo or Sugarcane Below and in front of observer. 
4. Plants then grow in front of the Observer. 
3. Signal Gets sent to Repeaters and goes through to the Sticky Piston.
4. Piston moves its block into the Sugar Cane or Bamboo block, and error appears.

**Expected behavior**
I expected no error at all because the repeaters are set to a delay of 4.

**Screenshots**
![0tick](https://user-images.githubusercontent.com/3103344/99915550-fc6d4400-2cc9-11eb-9148-3f649e057e76.png)
![0tick2](https://user-images.githubusercontent.com/3103344/99915552-0000cb00-2cca-11eb-80b9-c4b1fe609e42.png)
![0tick3-error](https://user-images.githubusercontent.com/3103344/99915556-05f6ac00-2cca-11eb-90e7-0e9097cf6c23.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.4  (paper-279.jar)
 - Client version: 1.16.4 Vanilla
 - Plugin version: Wraith 2.0.31

**Additional context**
No additional issues noted

**Comment by LoneDev6** [comment]
You can safely disable the 0 tick check in plugin config as Spigot fixed the 0 tick bug in 1.16.1+ versions ;)
Thanks for the report!

clients-config.yml
```yml
anti-dupe:
  0tick-farm:
    enabled: true
```
