### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ivettewo** [LoneDev6/Issues-Wraith#22]
Anti-cheat does not see cheats. 
On the video, cheats are blocked, on the server, the plugin issues errors and blocks only for the fly.

I didn't understand some of the points, but I expected the anti-cheat to work the same way as shown in the video.
We took the same cheat that was on the video, but nothing worked.
Even Xray wasn't blocked.
The texturpack also worked through the cheat.

https://i.imgur.com/XN9F7Ro.png
https://i.imgur.com/7u1Jsgz.png

 - Server version: 1.12.2 Forge
 - Client version: 1.12.2 ForgeOptifine
 - Plugin version: latest

For some problems, it issues a message in the console. For example, when a player tries to do so that he would not be dealt damage. But the main functions of the cheats work without problems - this is bad.

**Comment by LoneDev6** [comment]
Wait are you using Forge as server?
Can I get a full log?
Thanks

**Comment by ivettewo** [comment]
It'll take a while, g me 5-6 hours

**Comment by ivettewo** [comment]
I apologize. There was no time at all to make a separate log
[latest.log](https://github.com/PluginBugs/Issues-Wraith/files/5861839/latest.log)
[debug.log](https://github.com/PluginBugs/Issues-Wraith/files/5861840/debug.log)

**Comment by ivettewo** [comment]
esp/ bhop/ jesus mod/ xray work good

**Comment by ivettewo** [comment]
Mate ?

**Comment by ivettewo** [comment]
CAN U HELP ME ?

**Comment by LoneDev6** [comment]
> 
> 
> esp/ bhop/ jesus mod/ xray work good

I've just noticed this message (I got flooded with requests recently). I don't have any idea of where you read that Wraith anticheat supports esp, bhop and xray. All detected hacks are listed in the plugin page.
![immagine](https://user-images.githubusercontent.com/27242001/106361108-7817ec80-631c-11eb-9ef6-414be5a62371.png)
And tested clients also.
![immagine](https://user-images.githubusercontent.com/27242001/106361114-7d753700-631c-11eb-84a5-195c5818552b.png)


It's also a good idea to include the clients names you're using, each one uses a different method to hack.
Thanks

**Comment by LoneDev6** [comment]
I also just noticed you're using something called "Tablecloth" which is clearly not Spigot... I'm sorry but I can't know each of the existing Spigot alternatives on the web.
My plugin supports SpigotMC and Paper, other forks are not officially supported and I have no control on them, I cannot make the plugin compatible with each of the forks out there.

If you want you can ask for a refund, but keep in mind that every plugin on Spigot will be unstable on these unofficial builds.

Have a nice day
