### ISSUE TITLE
[Suggestion] -Permission to see kick-mods ingame

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#24]
client-config.yml has a nice capture of mods where it kicks the player if he tries to join with.
currently we just can view this in console.
It would be nice to have a permission to get this text that is posted to consolee have ingame chat too.
this is more comforable then looking into console each time, and also would give us the cnage to let see how staff members the reasons why a player may logged in/off so fast.
So pls add inagem chat view permissions for this

`>.... [13:48:31 INFO]: Joined -> Morphowolf | Brands: [fabric] | GameMode: SURVIVAL | World: tutorial | Location: /tppos -104 49 208 | UUID: 3420929b-499a-4bfe-8182-272974dc028d | IP: /80.210.79.146:59485`

![image](https://user-images.githubusercontent.com/12080017/107954909-629df600-6f9d-11eb-9874-f7ada4adb08e.png)
(looks sooooo great in console)

But please make it possible that its just pasted, when the player got kicked off. we dont want the infos from all vanilla clients in our ingame chat ;)

these options for the clients-config.yml, 
```
    notification:
      only-kicked-mods: false
      op: false
      permission: false
      console: false
```

**Comment by LoneDev6** [comment]
Will be added in the next update, thanks for the suggestion
