### ISSUE TITLE
[Suggestion] Reload command

### ISSUE THREAD

**Issue by EchoGravity** [LoneDev6/Issues-Wraith#3]
Add a reload feature to the plugin so if you decide to change the config you don't have to restart the server or reload with plugman.

EG: /ww reload

**Comment by CloudeLecaw** [comment]
u can use a pluginmanager ^^
Well it shows a error since beginnung now on reloading but finaly it reloads xD

**Comment by LoneDev6** [comment]
actually there already is a reload command, for now it's inside the settings GUI
`/ww settings` and press the reload button
