### ISSUE TITLE
[Suggestion] disable ingame post of Vanilla clients

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#38]
Maybe its allready possible and i know some hackclients might tell they are vanilla..
but for our staff its a bit to much that they see in chat every login even if its vanilla.
More interesting would be if they jsut got informed for the others

So is there a way to disable this ingame for "real" vanilla clients?
There might be allready an option and i just didnt found out how...

If not it would be nice if you could add this exeptions (maybe a whitelist?)

**Comment by LoneDev6** [comment]
So basically anything other than "vanilla" should be logged in chat if configured in config?
I think it's a good idea, for now if the brand is not in the config it's only shown in console not chat, so I think it's a good suggestion

**Comment by CloudeLecaw** [comment]
but i didnt saw a brand valled vanilla in config just Vanilla
![Snag_341f190](https://user-images.githubusercontent.com/12080017/120393223-dc31d800-c331-11eb-9f21-d63d341e54e0.png)

This is our chat (admins chat) when a player with vanilla comes online...we see it..for each normal player :3  and i saw nothing in config where i can disable it for just the vanilla clients
