### ISSUE TITLE
[BUG] Cannot invoke "dev.lone.wraith.h.a.d.a.a.K()" because "dev.lone.wraith.h.a.d.a.a.a" is null

### ISSUE THREAD

**Issue by mojiansheng** [LoneDev6/Issues-Wraith#39]
**Expected behavior**
Players can enter the server.
**Screenshots**
![image](https://user-images.githubusercontent.com/33216288/120815429-61abc700-c582-11eb-9c12-b8086ce9abfd.png)
![image](https://user-images.githubusercontent.com/33216288/120816311-383f6b00-c583-11eb-9ee7-4702a068a54e.png)
![image](https://user-images.githubusercontent.com/33216288/120816479-5a38ed80-c583-11eb-8673-91497e6789be.png)

**Info (please complete the following information):**
 - Server version: ( paper 1.16.5)
 - Client version: ( forge1.16.4)
 - Plugin version: (2.2.2)
**Additional context**
The plug-ins installed are:
LoneLibs  packetlimiter  ProtocolLib  Wraith

**Comment by LoneDev6** [comment]
please send the complete log, thanks!
there may be a mistake or the paper version is old.

thanks

**Comment by mojiansheng** [comment]
> please send the complete log, thanks!
> there may be a mistake or the paper version is old.
> 
> thanks

I send my server to you。
This is Download link:
*****

**Comment by LoneDev6** [comment]
Try to update paper, you're running a very old version
https://papermc.io/downloads

**Comment by mojiansheng** [comment]
> Try to update paper, you're running a very old version
> https://papermc.io/downloads

This is the latest version.
I don't running a old version

**Comment by mojiansheng** [comment]
> > please send the complete log, thanks!
> > there may be a mistake or the paper version is old.
> > thanks
> 
> I send my server to you。
> This is Download link:

The date on the screenshot is May 16. I use the paper of June 5th

> Try to update paper, you're running a very old version
> https://papermc.io/downloads

![image](https://user-images.githubusercontent.com/33216288/121031723-31ac3000-c7dd-11eb-8015-19aaed97723e.png)
This is the latest version I just downloaded to test.

**Comment by mojiansheng** [comment]
> > > please send the complete log, thanks!
> > > there may be a mistake or the paper version is old.
> > > thanks
> > 
> > 
> > I send my server to you。
> > This is Download link:
> 
> The date on the screenshot is May 16. I use the paper of June 5th
> 
> > Try to update paper, you're running a very old version
> > https://papermc.io/downloads
> 
> ![image](https://user-images.githubusercontent.com/33216288/121031723-31ac3000-c7dd-11eb-8015-19aaed97723e.png)
> This is the latest version I just downloaded to test.

http://52mc.top:808/nextcloud/index.php/s/6WBdZN9wnSstNyq

**Comment by LoneDev6** [comment]
In the log I read `This server is running Paper version git-Paper-682 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

paper 682 is old. last one is 770
https://papermc.io/downloads

**Comment by mojiansheng** [comment]
> In the log I read `This server is running Paper version git-Paper-682 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
> 
> paper 682 is old. last one is 770
> https://papermc.io/downloads

http://52mc.top:808/nextcloud/index.php/s/6WBdZN9wnSstNyq
you see this.

**Comment by mojiansheng** [comment]
> In the log I read `This server is running Paper version git-Paper-682 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
> 
> paper 682 is old. last one is 770
> https://papermc.io/downloads

![image](https://user-images.githubusercontent.com/33216288/121043695-70df7e80-c7e7-11eb-8a57-6636fa70d09b.png)

**Comment by LoneDev6** [comment]
Can you try to redownload wraith again? it may be corrupted.
Anyway the issue is that seems the plugin can't recognize Paper correctly.. it's very strange, something is wrong in the server configuration/jar file

**Comment by mojiansheng** [comment]
> Can you try to redownload wraith again? it may be corrupted.
> Anyway the issue is that seems the plugin can't recognize Paper correctly.. it's very strange, something is wrong in the server configuration/jar file

I've tried many times. At present, only 2.0.34 is normal. Other versions higher than this one can't run.

**Comment by mojiansheng** [comment]
Can you give me a paper containing Wraith?

**Comment by LoneDev6** [comment]
Can you try on another PC or on a remote server?

**Comment by mojiansheng** [comment]
> Can you try on another PC or on a remote server?

I have tried on three servers, and this error will be reported every time.
only 2.0.34 is normal.

**Comment by LoneDev6** [comment]
I can't find a reason why this happens sincerely.
This plugin works on all other servers, I have no idea on why this happens only on your server.
Apologizes.

**Comment by mojiansheng** [comment]
> I can't find a reason why this happens sincerely.
> This plugin works on all other servers, I have no idea on why this happens only on your server.
> Apologizes.

You pack up a latest download link for me, do you chat with TG? I add you friends.my TG number is mojiansheng

**Comment by LoneDev6** [comment]
What I did is downloading last Paper from the link I sent, run the server, no issue.
I'm using Java 8 on a PC with english language, it may be a problem with the system language?
I really have no idea, it doesn't happen on other servers

**Comment by LoneDev6** [comment]
Can also be a problem of java installation

**Comment by mojiansheng** [comment]
> 也可能是java安装的问题。



> Can also be a problem of java installation

I provide one of my servers
IP：103.117.138.185
user：administrator
pass：AAAaaa
Can you install the latest paper1.16.5 on it？

**Comment by mojiansheng** [comment]
> Can also be a problem of java installation

XXXXXXXXXXXXXXXX
Can you install the latest paper1.16.5 on it？

**Comment by LoneDev6** [comment]
Open a ticket on my discord server, don't share private info online.
Thanks.

Also provide me FTP and SSH access on the ticket: https://support.devs.beer

**Comment by mojiansheng** [comment]
> Open a ticket on my discord server, don't share private info online.
> Thanks.
> 
> Also provide me FTP and SSH access on the ticket: https://support.devs.beer

I can't send you a message on discounts
