### ISSUE TITLE
[BUG] Config Spider

### ISSUE THREAD

**Issue by BartosB13** [LoneDev6/Issues-Wraith#53]
Hey, I found a little problem with the wraith plugin.
I wanted to disable "spider" detection but always after a reload or reboot, the "enable" option comes back by itself from "false" to "true"

All other options appear to be working fine. The only problem is "spider detect"

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: vanilla
 - Plugin version: 2.2.6

Best Regards

**Comment by LoneDev6** [comment]
Should be fixed in 2.2.8
