### ISSUE TITLE
[BUG] False flags

### ISSUE THREAD

**Issue by Aveng3ful** [LoneDev6/Issues-Wraith#54]
I'm using Spigot 1.17.1 on my server, I've got Wraith installed & working, if my players are in boats, or jumping over lilypads etc they get kicked for jesus, flying or speed hacks.

I'm trying to figure out a way inside the Anti-cheat to make it less sensitive but I don't think I can? I'd appreciate any assistance.

**Comment by LoneDev6** [comment]
Is this still happening on latest versions of the plugin?
