### ISSUE TITLE
 Wraith is behaving incorrectly   :\ [BUG] 

### ISSUE THREAD

**Issue by Nerner12** [LoneDev6/Issues-Wraith#59]
Hello! Experiencing strange issues with the Wraith anti-cheat plugin. 

After installing the plugin, any attempt to log in with Forge (even without mods), the player receives a message not that Forge is prohibited on this server, but _**"Connection closed - mismatched mod channel list"**_.Despite the fact that the core of the server itself does not support mods. This happens even if you _disable checking for Forge_ in the plugin configuration. 

This concerns _only_ Forge, the reaction to _Fabric_ is _exactly_ the same as in the description of the plugin. 
I'm sure it's Wraith because removing this plugin fixes the problem.

In addition, very rarely with Forge it turns out to go to the server, if you repeat the entrance to the game for a long time. In this case, you can get an absolutely adequate reaction from the Wraith plugin, such as checking for mods, client name, etc.Please, tell me how to fix it.

In addition to this, when the Wraith anti-cheat is installed, the volume of packets sent by users either changes itself, or the requirements for it constantly change. 
At the first attempt of the player to enter, the volume of the packet is 128, as configured by the server. 

All subsequent times the packet size is equal to 2, which does not meet the server's requirement and of course does not let the player pass. 

As soon as I change the required volume of data packets on the server, by 2, the volume of packets immediately becomes too large and again is not passed by the server. The problem is solved again by removing Wraith,
help me please.

Sorry for writing the message out of shape.

**Comment by LoneDev6** [comment]
I need more info as requested by the issue template:
- server log
- server version
- plugin version
- client version
- forge version

**Comment by Nerner12** [comment]
Hello, sorry for not answering for a long time (
I attach the server logs with a text file.
Server version - AiriplanePurpur 1.17.1
Wraith Plugin Version 2.2.6
Client version - 1.17.1 ForgeOptifine
Forge version - 37.1.1
I am attaching a screenshot of the plugin's reaction to Forge without any mods with the Forge check turned off
[latest (1).log](https://github.com/PluginBugs/Issues-Wraith/files/7837219/latest.1.log)
![image](https://user-images.githubusercontent.com/97148990/148728790-5a1f935e-70ea-4fbe-a513-76e40b644d39.png)
.

**Comment by LoneDev6** [comment]
Next update will have two new options: https://wraith.devs.beer/plugin-usage/fix-fabric-forge-kick
