### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by EchoGravity** [LoneDev6/Issues-Wraith#6]
Add an auto-ban feature for when Wraith thinks someone is 100% cheating it runs a custom command.

Add a ghost mode where wraith won't setback a player who triggers a check

**Comment by LoneDev6** [comment]
You can edit the handlers to ban instead of kicking, you can add as many handlers you want in the detections-config.yml file.
So you can add ban, kick, tempban.. anything you want.

Wraith doesn't teleport back users when they cheat
