### ISSUE TITLE
pls add supportfor 1.18.2[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#62]
For the moment all plugins
wraith
epicbackpack
and also RPGMarket deniey to load on spigot 1.18.2
i think the reason for it is that the LoneDevLibs itself is not loading for now in 1.18.2

**Comment by LoneDev6** [comment]
I have to check what changed, thanks.
I'll definitely work on 1.18.2 this week.
Thanks
