### ISSUE TITLE
[Suggestion] test client by a book

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#65]
I have an idea for the little kids who don't know how to pass the test client when they join the server.
maybe the book item in Minecraft might be the solution books can be open when players join the server and they must press done to pass the test client and after they press the done button it will teleport them to the selected teleport location.
may you check this solution for me and add it?

**Comment by LoneDev6** [comment]
It's actually a good idea, I might implement it in the next update after some tests

**Comment by Ofek270704** [comment]
> It's actually a good idea, I might implement it in the next update after some tests

thank you very much i very appreciate it and your hard work on great plugins

**Comment by Ofek270704** [comment]
When will you add this idea to the update?

**Comment by LoneDev6** [comment]
Minecraft 1.19+ clients doesn't support this kind of checking anymore so I doubt I will implement this feature that soon.
So it's not reliable.

Related to this https://github.com/PluginBugs/Issues-Wraith/issues/87
