### ISSUE TITLE
 The block in the left hand is staggered by the right hand.

### ISSUE THREAD

**Issue by bckd00r** [LoneDev6/Issues-Wraith#68]
I get a normal putable minecraft block in the OFFHAND slot and when I put the itemsadder block in my main hand it puts the vanilla block first and then sets the itemsadder block.

**To Reproduce**
1. take a regular minecraft block in your left hand
2. get a customblock for your main hand
3. and try to place it. 
4. and watch the video

**Expected behavior**
A priority must be defined for each block.

**Screenshots**
https://streamable.com/x4fnwf

**Info (please complete the following information):**
 - purpur(1.18.2)
 - Optifine 1.18.2 lates
 - itemsadder-3.1.2

**Additional context**
note: when we want to go into the grass and place blocks, it does not place it properly, this creates an error.

**Comment by LoneDev6** [comment]
Wrong Github page.
https://github.com/PluginBugs/Issues-ItemsAdder/issues
