### ISSUE TITLE
Although the block hardness is not adjusted, miner fatigue does not disappear.

### ISSUE THREAD

**Issue by bckd00r** [LoneDev6/Issues-Wraith#69]
**Describe the bug**
I'm creating a new Custom Block, almost everything works fine, but I can't prevent miner fatigue when breaking the custom block. It's a bug I removed it from the config but it doesn't work looks like it needs a minor fix.

**To Reproduce**
1. I created a custom block.
2. I set the config config properly.
3.I placed the block and broke it.

**Expected behavior**
If the hardness level is not set in the configuration file, it should not give miner fatigue at all.
A setting can be added for this in config.yml.
(customblock_break_slown_potion_effect: true/false)

**Screenshots**
![image](https://user-images.githubusercontent.com/48347237/167318530-927c497a-0a69-47d8-bd6a-bd83bdd75f69.png)

**Info (please complete the following information):**
 - purpur(1.18.2)
 - Optifine 1.18.2
 - ItemsAdder 3.1.3

If it can be added, the hardness level should be adjusted with the ItemsAdder API. (It would be so nice.)

**Comment by LoneDev6** [comment]
Wrong Github page.
https://github.com/PluginBugs/Issues-ItemsAdder/issues
