### ISSUE TITLE
[BUG] Client not detected - Meteor Client 1.18.2

### ISSUE THREAD

**Issue by Futodama** [LoneDev6/Issues-Wraith#71]
**Describe the bug**
This cheat client is not blocked, and also bypasses almost all checks. An attempt to block through the wiki guide is useless.

**To Reproduce**
Install it, and check: https://www.geroncraft.ru/meteor-client/

**Expected behavior**
Detection and blocking.

[clients-config.zip](https://github.com/PluginBugs/Issues-Wraith/files/8838700/clients-config.zip)

**Info (please complete the following information):**
 - Server version:
 This server is running Paper version git-Paper-341 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc1752f)
 - Client version: Fabric 1.18.2
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**
Config`s [config.zip](https://github.com/PluginBugs/Issues-Wraith/files/8838700/clients-config.zip)

**Comment by LoneDev6** [comment]
they probably are faking the client brand and using some other methods to avoid getting detected.

You might try to enable `try-kick-fabric-silently: true` in `clients-config.yml`, I see you disabled it.

There is nothing else I can do.
