### ISSUE TITLE
[BUG] Cannot connect to the server

### ISSUE THREAD

**Issue by kortex00** [LoneDev6/Issues-Wraith#72]
Every time when I connect to a server with Wraith enabled, I get kicked out with the error: <<Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 256>>

But when I unload "Wraith" using plugman error disappears and i can connect.

It started after I put the server on hosting. Everything worked fine with localhost.
Can something be done about it?

![image](https://user-images.githubusercontent.com/106887089/172067109-5df3936a-0228-45d4-a801-6cf19d0cfb9d.png)

Info:
 - Server version: paper 1.18.2
 - Client version:  vanilla 1.18.2
 - Plugin version: 2.3.0

**Comment by LoneDev6** [comment]
Make sure both servers have the same server jar, same viaversion version and same protocollib.
