### ISSUE TITLE
[BUG] Wraith is not starting up on 1.19 on the latest version

### ISSUE THREAD

**Issue by IshKaigen** [LoneDev6/Issues-Wraith#74]
Describe the bug
Wraith fails to start on Purpur 1.19 using your latest updated version. (2.3.1)

1. Start server.
2. Attempt to load plugin.

Info
 - Server version: Purpur 1.19
 - Client version: Minecraft 1.19
 - Plugin version: 2.3.1

Pastebin error log:
https://pastebin.com/vtpCsinJ

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/173578727-8a608f9e-0fc0-4bc2-b9c4-8e1419ec9b8b.png)
https://www.spigotmc.org/resources/%E2%9C%85-wraith-anticheat-%E2%9B%94%EF%B8%8F-haunts-every-cheater.66887/updates
