### ISSUE TITLE
lunar and badlion cant join when testclient

### ISSUE THREAD

**Issue by Ofek270704** [LoneDev6/Issues-Wraith#75]
lunar and badlion still can't join the server when testclient, my server is on 1.18.2, and still players cant join, those mods are not enabled.
![image](https://user-images.githubusercontent.com/67981835/173596747-65451221-ec5c-484e-a52a-d663ff76ffa6.png)

**Comment by Ofek270704** [comment]
May you fix it as soon as possible because I am losing players, all my players are using lunar, I don't really like this client but nowadays kids use those clients so I have no option.

**Comment by LoneDev6** [comment]
Wraith just reads what the client sends to the server.
It detected Forge, World Edit CUI and WorldDownloader.

**Comment by Ofek270704** [comment]
I know I disabled those things and still it doesn't work, it started to begin when they updated the client (when 1.19 was released) before that it was okay.

**Comment by BartosB13** [comment]
I also have this problem. Regardless of mod settings, Lunar is rejected.

**Comment by BartosB13** [comment]
I found a solution to the problem. It is the appropriate configuration.

For lunar to work, you need to edit the clients-config file:

1. "Forge" section
- brands -> fml: false
- channels -> FML | HS: false

With these two set to false, wraith allows Lunar to connect to the server in my case as far as Forge is concerned. Everything else can be true.

2. Section "worldeditcui"

- channels -> worldedit:cui: false

With this one setting, wraith allows Lunar to connect to the server in my case as far as World Edit CUI is concerned. Everything else can be true.

3. There is also a setting of the Lunar itself. But this is already described on the wiki, and here is no change in this case.

This is how it works for me. Any editing of the wraith config, changing the above options, everyone does it at their own risk.

**Comment by LoneDev6** [comment]
I have no idea why Lunar client sends forge + worldedit packets.
You should ask its developers.
