### ISSUE TITLE
[BUG] 1.19 vanilla players can't pass testclient

### ISSUE THREAD

**Issue by Alcrafter-YT** [LoneDev6/Issues-Wraith#77]
**Describe the bug**
When you /testclient a 1.19 player, you get an error in console that they sent a message with invalid signature and the player can't pass the test.

**To Reproduce**
1. Run /testclient on a vanilla player using 1.19
2. Have the player you tested, click the message
3. Look in the console/log
4. See error and that player didn't pass

**Expected behavior**
Testclient should work on all client versions and not kick vanilla players just because they are using 1.19.

**Screenshots**
![image](https://user-images.githubusercontent.com/64634451/178800198-0a1aef97-1a44-4f50-bf9c-4a47fc0773c2.png)

**Info (please complete the following information):**
 - Server version: Paper 1.19
 - Client version: Vanilla 1.19
 - Plugin version: 2.3.1

**Additional context**
If you join on the same server with 1.18(or below) using ViaVersion/Backwards, the detection works as it should. It's just the 1.19 players that are affected.

**Comment by LoneDev6** [comment]
This will be fixed, thanks
