### ISSUE TITLE
[Suggestion] Add an option to decrease the number of red squares in the testclient message

### ISSUE THREAD

**Issue by Alcrafter-YT** [LoneDev6/Issues-Wraith#79]
**Is your feature request related to a problem? Please describe.**
99% of my server (including me) uses a shorter chat than default(I made a poll and most use around 200px). The issue is that I am using the Wraith client detection as a way of checking players manually by moderators, and so it happens fairly often. Unfortunately, when using a shorter chat width, the red squares that get sent with it stack up into multiple rows. That makes the feature hard to use/read especially for newer players which is just frustrating and not a good experience. You have to scroll and fight in order to actually be able to read the message that tells you to click.

**Describe the solution you'd like**
I would like to be able to set the number of red squares that get sent. By default, 30 red squares get sent in every line. If you could add a config option for the server owner to be able to reduce this number to, e.g. 20 or every number that they think fits the server best, it would be wonderful.

**Describe alternatives you've considered**
Even better would be to be able to just configure the whole message as a block and not only the parts that contain words.

**Additional context**
![image](https://user-images.githubusercontent.com/64634451/178950959-1ae3a703-a2fd-4045-914e-72c9a548c1ea.png)

**Comment by LoneDev6** [comment]
Rejected since the chat checking is now deprecated on most recent Minecraft versions.
https://github.com/PluginBugs/Issues-Wraith/issues/87
