### ISSUE TITLE
Spammy console lastest version of Protocollib Build 580[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [LoneDev6/Issues-Wraith#81]
When using latest Wraith with Latest Protocollib version (580 Recommaent download on spigot page for 1.19 server)

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

The console spams many errors with wraith
https://www.toptal.com/developers/hastebin/apoqofufuz.properties

**Comment by CloudeLecaw** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/1779#issuecomment-1195924455

**Comment by LoneDev6** [comment]
Thanks for the report, this will be fixed as some point.
For now use the previous ProtocolLib version
