### ISSUE TITLE
[BUG] MC 1.19.2 testclient (auto-onjoin) not work

### ISSUE THREAD

**Issue by BartosB13** [LoneDev6/Issues-Wraith#87]
**Describe the bug**
In MC 1.19.2 you cannot click on a chat message during client test, totally nothing is happening. This is a serious problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/89303317/184517945-ba45039d-0a46-437f-a671-3848d6501dda.png)

**Info (please complete the following information):**
 - Server version: Paper 1.19.2
 - Client version: MC 1.19.2
 - Plugin version: 2.3.3

**Comment by Ofek270704** [comment]
me too same prob

**Comment by Ofek270704** [comment]
please fix it lonedev

**Comment by LoneDev6** [comment]
This was disabled in 2.3.4 since Minecraft 1.19+ doesn't support this trick to check if players are cheating anymore.
I can't do anything to restore the functionality sadly, Mojang's fault again.
