### ISSUE TITLE
[BUG] Important bug, using items in MC 1.19.2 - bow and food (and more?)

### ISSUE THREAD

**Issue by BartosB13** [LoneDev6/Issues-Wraith#89]
**Describe the bug**
I do not know how to accurately describe this error, but it is problematic. It is possible that this error affects more things than what I found. It's all about right-click interactions, the video below shows the problem exactly.

**Wraith bug using items MC 1.19.2:**
[https://youtu.be/Dxi7IggL6nw](url)

**Info (please complete the following information):**
 - Server version: Paper 1.19.2 #130
 - Client version: MC 1.19.2 vanilla
 - Plugin version: 2.3.3

**Comment by BartosB13** [comment]
Something made the problem go away. Maybe it's a question of the engine or other plugins. Maybe it can be analyzed somehow, was the Wraith involved in the problem?

**Comment by YTiceice** [comment]
I have this error too, but I am using MultiPaper

When I facing a block, I can't eat or perform other right-click actions, details in the video
[YouTube](https://youtu.be/90JCyKZHPxI)

plugins:
`Plugins (17): AntiPopup, BungeeGuard, ChatPreview, DiscordSRV, InvSee, LoneLibs, LuckPerms, Orebfuscator, PlaceholderAPI, PlayerLogger*, PlugManX (PlugMan), ProtocolLib, SlimeChunk*, TabTPS, TaiwanifyEveryItem, WorldEdit, Wraith`
version:
`This server is running MultiPaper version git-MultiPaper-"6ce43aa" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6ce43aa)`

**Comment by LoneDev6** [comment]
I cannot reproduce the issue
