### ISSUE TITLE
[Error getting implementation for class] 

### ISSUE THREAD

**Issue by LeLuniXx** [LoneDev6/Issues-Wraith#93]
**Describe the bug**
I installed the server with the Wraith plugin and all dependencies (last update). When starting the crash it after the Wraith plugin is loaded in the console.

**To Reproduce**
1. Install all available plugins and dependencies.
2. Start the Server
3. The server will crash after starting and loading the plugin

**Expected behavior**
Now that my server is very customized and has a lot of modified content, I expected that it wouldn't work right away. But I expect that it does what it should ^^

**Info (please complete the following information):**
 - Server version: (paper-1.19.3-370)
 - Plugin version: ("latest")
 - Lonelib version: ("latest")
 - Protocollib version: (latest 1.19 dev Build from Jenkins)

**The FULL Startup Log**
Note the attached file
[latest.log](https://github.com/PluginBugs/Issues-Wraith/files/10355596/latest.log)

**Comment by LoneDev6** [comment]
Hello and happy new year.
It's not updated to 1.19.3, it will be in the next weeks.
