### ISSUE TITLE
the killaura with the wraith anti cheat is not working

### ISSUE THREAD

**Issue by Abood8001** [LoneDev6/Issues-Wraith#94]
![Screenshot 2023-01-18 120918](https://user-images.githubusercontent.com/111961022/213143976-491e89c8-94fa-4349-a918-eeb53813da61.png)
**Describe the bug**

the killaura with the wraith anti cheat is not working

**Info (please complete the following information):**
 - Server version: paper 1.19
 - Client version: 1.19
 - Plugin version: 2.3.4

**Additional context**
also when joining the server it sends errors like this "Unabke to inercept a read client packet (java.lang.illegalArgumentException: unable to find a field null with the type come.mojang.authib.gameprofile in net.minecraft.network.protocol.login.packetlogininstart) occured in come.comphenix.protocol.injector.netty.channelinjector@49f3d2cb)"

**Comment by LoneDev6** [comment]
post your whole server log.

**Comment by Abood8001** [comment]
https://paste.shockbyte.com/uqudapurupibuwidarep
 here is all logs

‫في الأربعاء، 18 يناير 2023 في 1:07 م تمت كتابة ما يلي بواسطة ‪LoneDev‬‏ <‪
***@***.***‬‏>:‬

**Comment by Abood8001** [comment]
so ??

**Comment by LoneDev6** [comment]
Log expired.
Anyway if you're on 1.19 as stated in your initial message you have to update to 1.19.2, 1.19.3 or 1.19.4.
