### ISSUE TITLE
[BUG] the player kicks from the server on vanilla

### ISSUE THREAD

**Issue by TheSash1** [LoneDev6/Issues-Wraith#96]
spigot 1.12.2
The problem is that when I log on to the server on pure vanilla, it kicks me that I have forge mods... How to set up an anti-cheat so that this does not happen?

![Screenshot_23](https://user-images.githubusercontent.com/99161081/218218958-0e4a61d1-c899-40c6-889c-f910de9e3fe5.png)

**Comment by Dartume** [comment]
i have the same und i have disable the punishments and the AntiCheat kicks the Player, only after disable the client check with  
anti-hacks:
  enabled: false
in Clients-config stop the Kick.
