### ISSUE TITLE
[BUG] Not flagging any hacks

### ISSUE THREAD

**Issue by 11Nexuss** [LoneDev6/Issues-Wraith#97]
I was looking for a good anticheat for my 1.19.2 smp and it seems to not be working
I installed the plugins and the dependinces and it still dosent work so i got my friend to get on wurst (The client used in the video) and i got him to fly around it didnt kick him at all Please help me fix this as soon as possible 

I expect the anticheat to kick like it did in the video But no kicks or logs/flags at all

**Info (please complete the following information):**
 -Server version Spigot/1.19.2
 - Client version Wurst 1.19.3
 - Plugin version: 2.3.4

I would please like this to be fixed soon as this server is currently growing very quickly and i would like to have a good anticheat

**Comment by LoneDev6** [comment]
Let me know your spigot username so I can refund your purchase, the plugin is not actively worked on and some recent cheats might be able to bypass it.

**Comment by 11Nexuss** [comment]
Hey sorry i didnt see this so my spigot is  ezerer123 id like a refund if that is dooable

**Comment by LoneDev6** [comment]
Refunded!
